services:
  db:
    image: postgres:15-alpine
    container_name: capmatch_db_local
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=capmatch
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d capmatch"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: capmatch_redis_local
    command: redis-server --requirepass your-secure-redis-password
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "your-secure-redis-password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: capmatch_backend_local
    ports:
      - "8000:8000" # <-- Expose backend port
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db/capmatch
      - REDIS_HOST=redis
      - REDIS_PASSWORD=your-secure-redis-password
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        # Tell the frontend where the backend API is for local dev
        NEXT_PUBLIC_API_URL: "http://localhost:8000"
    container_name: capmatch_frontend_local
    ports:
      - "3000:3000" # <-- Expose frontend port
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
