"""Create report_cache table

Revision ID: 259998303a7e
Revises: 
Create Date: 2025-09-13 14:37:19.267293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '259998303a7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_cache',
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_index(op.f('ix_report_cache_cache_key'), 'report_cache', ['cache_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_cache_cache_key'), table_name='report_cache')
    op.drop_table('report_cache')
    # ### end Alembic commands ###